# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Възелът на Христо
email: archri@openmailbox.org
xmpp: archri@jabb.im
diaspora: archri@disp.org
description: > # this means to ignore newlines until "baseurl:"
  Това е моят възел в мрежата. Тук споделям някои от нещата, които ме вълнуват.
github_username:  archri

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# custom settings
collections:
  wild_plants:
    output: true
  computer_metaphors:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

  -
    scope:
      path: "js"
    values:
      layout: nill
  -
    scope:
      path: ""
      type: "wild_plants" # a collection in your site, in plural form
    values:
      layout: "wild_plant"
